import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex sm:flex-col flex-row h-screen">
          {/* Sidebar (Full width on mobile, 20% on desktop) */}
            <Sidebar />
          {/* Main Content (Full width on mobile, 80% on desktop) */}
          <main className="flex-1 bg-gray-100 dark:bg-gray-900">
            <div className="container mx-auto md:px-16">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
